### ISSUE TITLE
Watcher tries to move watched directory itself...

### ISSUE THREAD

**Issue by MartinTheWanderer** [splitbrain/Watcher#19]
Maybe just a dumb misconfiguration by a semi-noob (me ;-) )

I use Watcher to move photos from my Dropbox folder into my Darktable import folder as they come in
(emulating iCloud photostream as suggested in this thread:  https://discussions.apple.com/thread/3729503?start=15&tstart=0)

Relevant lines from watcher config:
`watch=/home/me/Dropbox/Camera Uploads`
`events=create,delete,modify,open`
`recursive=true`
`autoadd=true`
`command=mv $filename /home/me/Pictures/Darktable_Import`

The files are moved as intended, but Watcher seems to try to move the watched dir itself... 
Log is full of messages like: 

> mv: cannot move '/home/thewanderer/Dropbox/Camera Uploads' to '/home/thewanderer/Pictures/Darktable_Import/Camera Uploads': Directory not empty

(the dir is not empty because Watcher already tried to move the whole dir into the destination folder once before I stopped it.)

Also a lot of 

> mv: cannot stat '/home/me/Dropbox/Camera Uploads/2016-10-27 15.27.36 HDR.jpg': No such file or directory

Should the mv command look different, or is Watcher being quirky? ;-)

**Comment by Hretic** [comment]
i believe its becuz of space in the name of the files and directories
try this
command=mv "$filename" /home/me/Pictures/Darktable_Import

**Comment by MartinTheWanderer** [comment]
thanks for the ideas

probably really an issue with spaces and the sometimes not so logical way they are handled in Linux, specifically Ubuntu... 
Can't confirm right now since I ditched my Ubuntu anyways and moved on to Qubes/Debian... 
Will report back if I run into this issue again. 
cheers
